name: Pull Request Post-Commit Hook

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  post_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Post-Commit Hook
        run: |
          # Replace this with the actual command to run your post-commit script
          ./post-commit.sh
        continue-on-error: true

      - name: Set Failure Flag
        id: failure-flag
        run: echo "::set-output name=failure::true"
        when: ${{ failure() }}

  check_merge:
    runs-on: ubuntu-latest
    needs: post_commit
    steps:
      - name: Check Post-Commit Script Status
        run: |
          if [ "${{ needs.post_commit.outputs.failure }}" == "true" ]; then
            echo "Post-Commit Script Failed. Preventing Merge."
            exit 1
          fi



#name: Post-Commit Hook

#on:
#  push:
#    branches:
#      - main

#jobs:
#  post_commit:
#    runs-on: ubuntu-latest

#   steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Run Post-Commit Hook
#        run: |
          # Replace this with the actual command to run your post-commit script
#          ./post-commit.sh
